networks:
  aniway-network:
    driver: bridge

services:
  # Manga Service - для разработки с volume binding
  manga-service:
    build:
      context: ./MangaService
      dockerfile: Dockerfile.dev
    volumes:
      - ./MangaService/src:/app/src:ro
      - ./MangaService/build.gradle.kts:/app/build.gradle.kts:ro
      - gradle-cache-manga:/home/gradle/.gradle
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://manga-postgres:5432/manga_db
      - SPRING_DATASOURCE_USERNAME=manga_user
      - SPRING_DATASOURCE_PASSWORD=manga_password
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MELON_SERVICE_URL=http://melon-service:8084
      - MELON_SERVICE_PUBLIC_URL=http://192.168.0.3:8084
      - CHAPTER_SERVICE_URL=http://chapter-service:8082
      - IMAGE_STORAGE_SERVICE_URL=http://image-storage-service:8083
    ports:
      - "8081:8081"
    depends_on:
      manga-postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - aniway-network

  # Chapter Service - для разработки
  chapter-service:
    build:
      context: ./ChapterService
      dockerfile: Dockerfile.dev
    volumes:
      - ./ChapterService/src:/app/src:ro
      - ./ChapterService/build.gradle.kts:/app/build.gradle.kts:ro
      - gradle-cache-chapter:/home/gradle/.gradle
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://chapter-postgres:5432/chapter_db
      - SPRING_DATASOURCE_USERNAME=chapter_user
      - SPRING_DATASOURCE_PASSWORD=chapter_password
      - MANGA_SERVICE_URL=http://manga-service:8081
      - IMAGE_STORAGE_SERVICE_URL=http://image-storage-service:8083
    ports:
      - "8082:8082"
    depends_on:
      chapter-postgres:
        condition: service_healthy
    networks:
      - aniway-network

  # Image Storage Service - для разработки
  image-storage-service:
    build:
      context: ./ImageStorageService
      dockerfile: Dockerfile.dev
    volumes:
      - ./ImageStorageService/src:/app/src:ro
      - ./ImageStorageService/build.gradle.kts:/app/build.gradle.kts:ro
      - gradle-cache-image:/home/gradle/.gradle
      - melon_data:/app/Output  # Общий том с MelonService для доступа к скачанным изображениям
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://image-storage-postgres:5432/image_storage_db
      - SPRING_DATASOURCE_USERNAME=image_user
      - SPRING_DATASOURCE_PASSWORD=image_password
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_PUBLIC_ENDPOINT=http://192.168.0.3:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MANGA_SERVICE_URL=http://manga-service:8081
      - CHAPTER_SERVICE_URL=http://chapter-service:8082
    ports:
      - "8083:8083"
    depends_on:
      image-storage-postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - aniway-network

  # Gateway Service - для разработки
  gateway-service:
    build:
      context: ./GateWayService
      dockerfile: Dockerfile.dev
    volumes:
      - ./GateWayService/src:/app/src:ro
      - ./GateWayService/build.gradle.kts:/app/build.gradle.kts:ro
      - gradle-cache-gateway:/home/gradle/.gradle
    environment:
      - SPRING_PROFILES_ACTIVE=dev,docker
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - MANGA_SERVICE_URL=http://manga-service:8081
      - CHAPTER_SERVICE_URL=http://chapter-service:8082
      - IMAGE_STORAGE_SERVICE_URL=http://image-storage-service:8083
    ports:
      - "8080:8080"
    depends_on:
      - manga-service
      - chapter-service
      - image-storage-service
      - auth-service
      - comment-service
      - forum-service
      - notification-service
      - melon-service
    networks:
      - aniway-network

  # MelonService - парсер манги (dev режим)
  melon-service:
    build:
      context: ./MelonService
      dockerfile: Dockerfile.dev
    ports:
      - "8084:8084"
    volumes:
      - ./MelonService:/app
      - melon_data:/app/Output
      - melon_logs:/app/Logs
      - melon_temp:/app/Temp
    environment:
      - PYTHONPATH=/app
    networks:
      - aniway-network
    restart: unless-stopped

  # Auth Service - для разработки
  auth-service:
    build:
      context: ./AuthService
      dockerfile: Dockerfile.dev
    volumes:
      - ./AuthService/src:/app/src:ro
      - ./AuthService/build.gradle.kts:/app/build.gradle.kts:ro
      - gradle-cache-auth:/home/gradle/.gradle
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-postgres:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=auth_user
      - SPRING_DATASOURCE_PASSWORD=auth_password
      - JWT_SECRET=mySecretKey12345678901234567890123456789012345678901234567890
      - JWT_EXPIRATION=86400000
      - CORS_ALLOWED_ORIGINS=http://localhost:*,http://192.168.*.*:*,http://10.*.*.*:*
      - MANGA_SERVICE_URL=http://manga-service:8081
    ports:
      - "8085:8085"
    depends_on:
      auth-postgres:
        condition: service_healthy
    networks:
      - aniway-network

  # Comment Service - для разработки
  comment-service:
    build:
      context: ./CommentService
      dockerfile: Dockerfile.dev
    volumes:
      - ./CommentService/src:/app/src:ro
      - ./CommentService/build.gradle.kts:/app/build.gradle.kts:ro
      - gradle-cache-comment:/home/gradle/.gradle
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://comment-postgres:5432/comment_db
      - SPRING_DATASOURCE_USERNAME=comment_user
      - SPRING_DATASOURCE_PASSWORD=comment_password
      - JWT_SECRET=mySecretKey12345678901234567890123456789012345678901234567890
      - JWT_EXPIRATION=86400000
      - AUTH_SERVICE_URL=http://auth-service:8085
    ports:
      - "8086:8086"
    depends_on:
      comment-postgres:
        condition: service_healthy
    networks:
      - aniway-network

  # Frontend - для разработки с hot-reload
  frontend:
    build:
      context: ./AniWayFrontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./AniWayFrontend/src:/app/src
      - ./AniWayFrontend/public:/app/public
      - ./AniWayFrontend/package.json:/app/package.json:ro
      - ./AniWayFrontend/vite.config.ts:/app/vite.config.ts:ro
      - ./AniWayFrontend/tsconfig.json:/app/tsconfig.json:ro
      - ./AniWayFrontend/tailwind.config.js:/app/tailwind.config.js:ro
      - node_modules-cache:/app/node_modules
    ports:
      - "5173:5173"  # Vite dev server
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - manga-service
    networks:
      - aniway-network

  # PostgreSQL databases for development
  manga-postgres:
    image: postgres:16
    container_name: manga-postgres-dev
    environment:
      POSTGRES_DB: manga_db
      POSTGRES_USER: manga_user
      POSTGRES_PASSWORD: manga_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5435:5432"
    volumes:
      - manga_postgres_data:/var/lib/postgresql/data
      - ./MangaService/mangaDB.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - aniway-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U manga_user -d manga_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  chapter-postgres:
    image: postgres:16
    container_name: chapter-postgres-dev
    environment:
      POSTGRES_DB: chapter_db
      POSTGRES_USER: chapter_user
      POSTGRES_PASSWORD: chapter_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - chapter_postgres_data:/var/lib/postgresql/data
      - ./ChapterService/chapterDB.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - aniway-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chapter_user -d chapter_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  image-storage-postgres:
    image: postgres:16
    container_name: image-storage-postgres-dev
    environment:
      POSTGRES_DB: image_storage_db
      POSTGRES_USER: image_user
      POSTGRES_PASSWORD: image_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    volumes:
      - image_storage_postgres_data:/var/lib/postgresql/data
      - ./ImageStorageService/imageStorageDB.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - aniway-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U image_user -d image_storage_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-postgres:
    image: postgres:16
    container_name: auth-postgres-dev
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5436:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
      - ./AuthService/authDB.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - aniway-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  comment-postgres:
    image: postgres:16
    container_name: comment-postgres-dev
    environment:
      POSTGRES_DB: comment_db
      POSTGRES_USER: comment_user
      POSTGRES_PASSWORD: comment_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5437:5432"
    volumes:
      - comment_postgres_data:/var/lib/postgresql/data
      - ./CommentService/commentDB.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - aniway-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U comment_user -d comment_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Forum Service - for development (added to mirror prod environment)
  forum-service:
    build:
      context: ./ForumService
      dockerfile: Dockerfile.dev
    volumes:
      - ./ForumService/src:/app/src:ro
      - ./ForumService/build.gradle.kts:/app/build.gradle.kts:ro
      - gradle-cache-forum:/home/gradle/.gradle
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://forum-postgres:5432/forum_db
      - SPRING_DATASOURCE_USERNAME=forum_user
      - SPRING_DATASOURCE_PASSWORD=forum_password
      - JWT_SECRET=mySecretKey12345678901234567890123456789012345678901234567890
      - JWT_EXPIRATION=86400000
      - AUTH_SERVICE_URL=http://auth-service:8085
      - MANGA_SERVICE_URL=http://manga-service:8081
    ports:
      - "8087:8087"
    depends_on:
      forum-postgres:
        condition: service_healthy
      auth-service:
        condition: service_started
      manga-service:
        condition: service_started
    networks:
      - aniway-network

  # Notification Service - for development (added to mirror prod environment)
  notification-service:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile # no dev Dockerfile present, reuse prod
    volumes:
      - ./NotificationService/src:/app/src:ro
      - ./NotificationService/build.gradle:/app/build.gradle:ro
      - gradle-cache-notification:/home/gradle/.gradle
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://notification-postgres:5432/notification_db
      - SPRING_DATASOURCE_USERNAME=notification_user
      - SPRING_DATASOURCE_PASSWORD=notification_password
      # Internal service URLs to ensure chapter title enrichment, etc.
      - MANGA_SERVICE_INTERNAL_URL=http://manga-service:8081
      - CHAPTER_SERVICE_INTERNAL_URL=http://chapter-service:8082
      - NOTIFICATION_CHAPTER_DEDUPE_MODE=PER_CHAPTER
    ports:
      - "8095:8095"
    depends_on:
      notification-postgres:
        condition: service_healthy
      manga-service:
        condition: service_started
      chapter-service:
        condition: service_started
    networks:
      - aniway-network

  forum-postgres:
    image: postgres:16
    container_name: forum-postgres-dev
    environment:
      POSTGRES_DB: forum_db
      POSTGRES_USER: forum_user
      POSTGRES_PASSWORD: forum_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5438:5432"
    volumes:
      - forum_postgres_data:/var/lib/postgresql/data
      - ./ForumService/forumDB.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - aniway-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U forum_user -d forum_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  notification-postgres:
    image: postgres:16
    container_name: notification-postgres-dev
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: notification_user
      POSTGRES_PASSWORD: notification_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5439:5432"
    volumes:
      - notification_postgres_data:/var/lib/postgresql/data
    networks:
      - aniway-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notification_user -d notification_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MinIO for development
  minio:
    image: minio/minio:latest
    container_name: minio-dev
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - aniway-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MinIO initialization service
  minio-init:
    image: minio/mc:latest
    container_name: minio-init-dev
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./init-minio.sh:/init-minio.sh
    networks:
      - aniway-network
    entrypoint: >
      /bin/sh -c "
      sleep 10 &&
      mc alias set minio-local http://minio:9000 minioadmin minioadmin &&
      mc mb minio-local/manga-images --ignore-existing &&
      mc anonymous set public minio-local/manga-images &&
      echo 'MinIO initialization completed'
      "
    restart: "no"

volumes:
  gradle-cache-manga:
  gradle-cache-chapter:
  gradle-cache-image:
  gradle-cache-gateway:
  gradle-cache-auth:
  gradle-cache-comment:
  node_modules-cache:
  manga_postgres_data:
  chapter_postgres_data:
  image_storage_postgres_data:
  auth_postgres_data:
  comment_postgres_data:
  minio_data:
  melon_data:
  melon_logs:
  melon_temp:
  melon_logs_temp:
  melon_data_temp:
  forum_postgres_data:
  notification_postgres_data:
  gradle-cache-forum:
  gradle-cache-notification: