spring:
  datasource:
    url: jdbc:postgresql://manga-postgres:5432/mangadb?useUnicode=true&characterEncoding=UTF-8
    username: mangauser
    password: mangapass123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": true

# Other services URLs (using Docker service names)
chapter:
  service:
    url: ${CHAPTER_SERVICE_URL:http://chapter-service:8082}

# Services configuration
services:
  auth-service-url: ${AUTH_SERVICE_URL:http://auth-service:8085}
  chapter-service-url: ${CHAPTER_SERVICE_URL:http://chapter-service:8082}
  image-storage-service-url: ${IMAGE_STORAGE_SERVICE_URL:http://image-storage-service:8083}
  melon-service-url: ${MELON_SERVICE_URL:http://melon-service:8084}
  melon-service-public-url: http://84.201.152.162:8084

# Logging for debugging service communication
logging:
  level:
    "[com.aniway.mangaservice]": INFO
    "[com.aniway.mangaservice.client]": INFO
    "[org.springframework.web.client]": INFO
    "[org.apache.http]": INFO
    "[shadowshift.studio.mangaservice]": INFO
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
