package shadowshift.studio.notificationservice.domain;

public enum NotificationType {
    REPLY_TO_COMMENT,
    NEW_COMMENT_ON_USER_FORUM_THREAD,
    REPLY_IN_FORUM_THREAD,
    COMMENT_ON_REVIEW,
    PROFILE_COMMENT,
    BOOKMARK_NEW_CHAPTER,
    FRIEND_REQUEST_RECEIVED,
    FRIEND_REQUEST_ACCEPTED,
    DIRECT_MESSAGE,
    DIRECT_MESSAGE_REPLY,
    CHANNEL_MESSAGE_REPLY,
    MOMENT_LIKE,
    MOMENT_COMMENT,
    MOMENT_REPLY
}
