server:
  port: 8080

auth:
  introspect-url: "http://auth-service:8085/api/auth/validate"
  public-paths: "/api/auth/**,/auth/**,/api/health/**,/api/public/**,/parser,/parser/**,/api/parser/**,/api/parser/progress/**,/manga,/manga/**,/api/genres/**,/api/tags/**,/api/notifications/stream,/api/levels/**,/api/import-queue/**"
  cache-ttl-seconds: 300

spring:
  application:
    name: gateway-service

  # File upload configuration for Gateway
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 2GB

  cloud:
    gateway:
      # Глобальные CORS настройки
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: 
              - "http://localhost:*"  # Все localhost порты
              - "http://192.168.*.*:*" # Вся локальная сеть 192.168.x.x
              - "http://10.*.*.*:*"    # Вся локальная сеть 10.x.x.x
              - "http://172.16.*.*:*"  # Частная сеть 172.16.x.x
              - "http://172.17.*.*:*"  # Docker сеть 172.17
              - "http://172.18.*.*:*"  # Docker сеть 172.18
              - "http://aniway.space"    # Прод домен HTTP
              - "https://aniway.space"   # Прод домен HTTPS
              - "http://www.aniway.space"  # WWW HTTP
              - "https://www.aniway.space" # WWW HTTPS
              - "http://*.yandexcloud.net" # Yandex Cloud
              - "https://*.yandexcloud.net" # Yandex Cloud HTTPS
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
            allowed-headers:
              - "*"
            allow-credentials: true
            max-age: 3600

      # Маршруты к микросервисам (для Docker)
      routes:
        # MangaService - WebSocket endpoints (НАИВЫСШИЙ ПРИОРИТЕТ)
        - id: manga-websocket
          uri: ws://manga-service:8081
          predicates:
            - Path=/api/manga/ws/**
          filters:
            - StripPrefix=3  # Исправляем: удаляем /api/manga/ws, оставляем /progress
          order: 0

        # AuthService - Authentication and user management (HIGH PRIORITY)
        - id: auth-api
          uri: http://auth-service:8085
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0
          order: 1

        # AuthService - Alternate path without /api prefix
        - id: auth-api-alt
          uri: http://auth-service:8085
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
          order: 1

        # AuthService - User management
        - id: users-api
          uri: http://auth-service:8085
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0
          order: 2

        # AuthService - Bookmarks
        - id: bookmarks-api
          uri: http://auth-service:8085
          predicates:
            - Path=/api/bookmarks/**
          filters:
            - StripPrefix=0
          order: 3

        # AuthService - Reading progress
        - id: progress-api
          uri: http://auth-service:8085
          predicates:
            - Path=/api/progress/**
          filters:
            - StripPrefix=0
          order: 4

        # AuthService - Admin utilities
        - id: admin-utils-api
          uri: http://auth-service:8085
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=0
          order: 5

        # PostService - Posts API
        - id: posts-api
          uri: http://post-service:8097
          predicates:
            - Path=/api/posts/**
          filters:
            - StripPrefix=0
          order: 6

        # MangaService - API endpoints
        - id: manga-api
          uri: http://manga-service:8081
          predicates:
            - Path=/api/manga/**
          filters:
            - StripPrefix=0

        # MangaService - Genres API
        - id: genres-api
          uri: http://manga-service:8081
          predicates:
            - Path=/api/genres/**
          filters:
            - StripPrefix=0
          order: 8

        # MangaService - Tags API  
        - id: tags-api
          uri: http://manga-service:8081
          predicates:
            - Path=/api/tags/**
          filters:
            - StripPrefix=0
          order: 9

        # MangaService - Import Queue API
        - id: import-queue-api
          uri: http://manga-service:8081
          predicates:
            - Path=/api/import-queue/**
          filters:
            - StripPrefix=0
          order: 10

        # MangaService - Web UI (Thymeleaf страницы)
        - id: manga-web
          uri: http://manga-service:8081
          predicates:
            - Path=/manga,/manga/**
          filters:
            - StripPrefix=0

        - id: manga-web-parser
          uri: http://manga-service:8081
          predicates:
            - Path=/parser,/parser/**
          filters:
            - StripPrefix=0

        # MangaService - Reader
        - id: manga-reader
          uri: http://manga-service:8081
          predicates:
            - Path=/reader/**
          filters:
            - StripPrefix=0

        # MangaService - Chapters Web UI
        - id: chapters-web
          uri: http://manga-service:8081
          predicates:
            - Path=/chapters/**
          filters:
            - StripPrefix=0

        # ChapterService - API endpoints
        - id: chapter-api
          uri: http://chapter-service:8082
          predicates:
            - Path=/api/chapters/**
          filters:
            - StripPrefix=0

        # ImageStorageService - API endpoints
        - id: images-api
          uri: http://image-storage-service:8083
          predicates:
            - Path=/api/images/**
          filters:
            - StripPrefix=0

        # CommentService - API endpoints
        - id: comments-api
          uri: http://comment-service:8086
          predicates:
            - Path=/api/comments/**
          filters:
            - StripPrefix=0

        # FriendService - Friends API
        - id: friends-api
          uri: http://friend-service:8102
          predicates:
            - Path=/api/friends/**
          filters:
            - StripPrefix=0

        # MessageService - Messaging API
        - id: messages-api
          uri: http://message-service:8103
          predicates:
            - Path=/api/messages/**
          filters:
            - StripPrefix=0

        # LevelService - Levels & Badges API endpoints
        - id: levels-api
          uri: http://level-service:8098
          predicates:
            - Path=/api/levels/**
          filters:
              - StripPrefix=1

        # MangaService - Parser API endpoints (через MangaService для правильной интеграции)
        - id: manga-parser
          uri: http://manga-service:8081
          predicates:
            - Path=/api/parser/**
          filters:
            - StripPrefix=1
          order: 5

        - id: notification-api
          uri: http://notification-service:8095
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=0

        # Статические ресурсы MangaService (favicon, CSS, JS)
        - id: manga-static
          uri: http://manga-service:8081
          predicates:
            - Path=/favicon.ico,/static/**,/css/**,/js/**,/images/**
          filters:
            - StripPrefix=0

      # Настройки тайм-аутов
      httpclient:
        connect-timeout: 10000
        response-timeout: 60000  # Увеличиваем до 60 секунд для долгих операций парсинга

# Actuator для мониторинга
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

# Логирование
logging:
  level:
    '[org.springframework.cloud.gateway]': INFO
    '[org.springframework.web]': WARN
    '[shadowshift.studio]': INFO
